version: '3'
services:

  db:
    image: postgres:13.0
    env_file:
      - ./.env
    volumes:
      - postgres_vol:/var/lib/postgresql/data/

  backend:
    image: vladvorobyeff/foodgram_backend
    volumes:
      - static_vol:/app/static/
      - media_vol:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always
    container_name: foodgram_backend

  frontend:
    image: vladvorobyeff/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend


  nginx:
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
    depends_on:
      - backend
      - frontend
    container_name: foodgram_nginx

volumes:
  postgres_vol:
  static_vol:
  media_vol:
